<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <RootNamespace>EmbyProxy</RootNamespace>
    <AssemblyName>EmbyProxy</AssemblyName>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\thumb.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="mediabrowser.server.core" Version="4.8.11" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <BuildDate>$([System.DateTime]::UtcNow.AddHours(8).ToString("yyyy-MM-dd HH:mm"))</BuildDate>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>BuildDate</_Parameter1>
      <_Parameter2>$(BuildDate)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /Y /Q &quot;$(TargetDir)$(TargetFileName)&quot; &quot;%25AppData%25\Emby-Server\programdata\plugins\&quot;" />
  </Target>
</Project>
